---
name: TorrServer
version: 0.1.3
slug: torrserver
description: TorrServer for home assistant
url: https://github.com/g470258/hassio-torrserver
codenotary: aatrubilin@gmail.com
#webui: http://[HOST]:[PORT:8090]
#webui: "[PROTO:ssl]://[HOST]:[PORT:8090]"
ingress: true
#ingress_port: 8090
ingress_stream: true
init: false
auth_api: true
arch:
  - armv7
  - amd64
  - i386
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: TorrServer Web
map:
  - share:rw
