---
name: TorrServer
version: 0.1.1
slug: torrserver
description: TorrServer for home assistant
url: https://github.com/zamarawka/hassio-torrserver
codenotary: somebody.told@mail.ru
webui: http://[HOST]:[PORT:8090]
init: false
auth_api: true
arch:
  - armv7
  - amd64
  - i386
ports:
  8090/tcp: 8090
ports_description:
  8090/tcp: TorrServer Web
map:
  - share:rw
